import type {
  BioCoreContent,
  EpkPdfContent,
  EpkPhotoSlot,
  Gig,
  MusicLink,
  VideoRow,
} from "./types";

const seededAt = "2026-07-02T00:00:00.000Z";

export const defaultGigs: Gig[] = [
  {
    id: "aberdeen-jazz-festival",
    event_date: "2026-03-15",
    title: "ABERDEEN JAZZ FESTIVAL",
    location: "Aberdeen, Scotland",
    lineup_preset: "SOLO",
    lineup_custom_label: "",
    time_label: "DAY SHOW",
    ticket_url: "",
    order_index: 0,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "the-jazz-bar",
    event_date: "2026-03-22",
    title: "THE JAZZ BAR",
    location: "Edinburgh, Scotland",
    lineup_preset: "TRIO",
    lineup_custom_label: "",
    time_label: "7:30PM",
    ticket_url: "",
    order_index: 1,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "kelburn-garden-party",
    event_date: "2026-04-05",
    title: "KELBURN GARDEN PARTY",
    location: "Argyll, Scotland",
    lineup_preset: "TRIO",
    lineup_custom_label: "",
    time_label: "2:00PM",
    ticket_url: "",
    order_index: 2,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "st-lukes",
    event_date: "2026-04-18",
    title: "ST LUKES",
    location: "Glasgow, Scotland",
    lineup_preset: "DUO",
    lineup_custom_label: "",
    time_label: "8:00PM",
    ticket_url: "",
    order_index: 3,
    created_at: seededAt,
    updated_at: seededAt,
  },
];

export const defaultVideos: VideoRow[] = [
  {
    id: "cVnYnMeSUhw",
    title: "Rivkala - All I Should Expect (Official Video)",
    youtube_url: "https://www.youtube.com/watch?v=cVnYnMeSUhw",
    youtube_id: "cVnYnMeSUhw",
    is_featured: false,
    order_index: 0,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "LK7PeIOZiVY",
    title: "Rivkala - Chess (Official Video)",
    youtube_url: "https://www.youtube.com/watch?v=LK7PeIOZiVY",
    youtube_id: "LK7PeIOZiVY",
    is_featured: true,
    order_index: 1,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "TnpmmD1SJCY",
    title: "Rivkala - Vultures (Official Video)",
    youtube_url: "https://www.youtube.com/watch?v=TnpmmD1SJCY",
    youtube_id: "TnpmmD1SJCY",
    is_featured: false,
    order_index: 2,
    created_at: seededAt,
    updated_at: seededAt,
  },
];

export const defaultMusicLinks: MusicLink[] = [
  {
    id: "crushed-velvet",
    title: "Crushed Velvet",
    is_featured: false,
    release_type: "EP",
    release_year: 2025,
    description: "Late nights, soft lights, and the things we pretend not to feel.",
    url: "https://rivkala.bandcamp.com/album/crushed-velvet",
    spotify_url: "https://open.spotify.com/artist/3w2AbU8fkyaeDHlBLgCq0x",
    apple_music_url: "https://music.apple.com/gb/album/crushed-velvet/1814113241",
    bandcamp_url: "https://rivkala.bandcamp.com/album/crushed-velvet",
    youtube_url: "",
    shop_variant_id: "",
    sale_enabled: false,
    price_gbp: 0,
    download_mp3_key: "",
    download_wav_key: "",
    thumbnail_src: "/Album%20covers/Crushed%20Velvet.png",
    thumbnail_alt: "Crushed Velvet cover artwork",
    order_index: 0,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "chess",
    title: "Chess",
    is_featured: false,
    release_type: "SINGLE",
    release_year: 2024,
    description: "A game of strategy, ego, and endings we saw coming.",
    url: "https://rivkala.bandcamp.com/track/chess",
    spotify_url: "https://open.spotify.com/artist/3w2AbU8fkyaeDHlBLgCq0x",
    apple_music_url: "https://music.apple.com/gb/album/chess-single/1770338131",
    bandcamp_url: "https://rivkala.bandcamp.com/track/chess",
    youtube_url: "https://www.youtube.com/watch?v=LK7PeIOZiVY",
    shop_variant_id: "",
    sale_enabled: false,
    price_gbp: 0,
    download_mp3_key: "",
    download_wav_key: "",
    thumbnail_src: "/Album%20covers/Chess.png",
    thumbnail_alt: "Chess cover artwork",
    order_index: 1,
    created_at: seededAt,
    updated_at: seededAt,
  },
  {
    id: "zip-lock-teeth",
    title: "Zip Lock Teeth",
    is_featured: false,
    release_type: "SINGLE",
    release_year: 2024,
    description: "Bittersweet and a little unhinged: love, insecurity, and the snap when it seals shut.",
    url: "https://rivkala.bandcamp.com/track/zip-lock-teeth",
    spotify_url: "https://open.spotify.com/artist/3w2AbU8fkyaeDHlBLgCq0x",
    apple_music_url: "https://music.apple.com/gb/album/zip-lock-teeth-single/1790238863",
    bandcamp_url: "https://rivkala.bandcamp.com/track/zip-lock-teeth",
    youtube_url: "",
    shop_variant_id: "",
    sale_enabled: false,
    price_gbp: 0,
    download_mp3_key: "",
    download_wav_key: "",
    thumbnail_src: "/Album%20covers/Zip%20Lock%20Teeth.png",
    thumbnail_alt: "Zip Lock Teeth cover artwork",
    order_index: 2,
    created_at: seededAt,
    updated_at: seededAt,
  },
];

export const defaultBioCore: BioCoreContent = {
  pronunciation: "RIV-kuh-luh",
  pronouns: "she / her",
  strapline: "Showgirl, singer and storyteller",
  shortBio:
    "Rivkala is an award-winning multidisciplinary jazz and soul artist, vocalist, writer and bandleader. From the campy cabaret world of Crushed Velvet, she and her six-piece band blend jazz, soul, funk and klezmer into provocatively playful songs about gender, wealth inequality and mental health. Serious grooves meet theatrical wit beneath the warm glow of her beloved lamp, Lucille.",
  longBio: [
    "Born in Manchester and based in Newcastle, Rivkala builds vivid, theatrical worlds around soulful melodies, sharp observational writing and a larger-than-life cabaret presence. Her work turns everyday frustrations into playful social commentary without losing sight of the groove.",
    "Alongside her six-piece band, she has appeared at BBC Proms performances, Manchester Jazz Festival, the MOBO fringe festival and the SXSW Roadshow, and has supported Postmodern Jukebox at The Glasshouse International Centre for Music. Her music has received coverage from BBC Radio 3, Jazz FM, Selector Radio and BBC Introducing.",
  ],
};

export const defaultEpkPdf: EpkPdfContent = {
  href: "/api/media/epk-pdf/RIVKALA_EPK_OFFICIAL.pdf",
  downloadName: "RIVKALA EPK OFFICIAL.pdf",
};

export const defaultEpkPhotoSlots: EpkPhotoSlot[] = [
  {
    slot: 1,
    src: "/IMAGES%20OF%20ME/Rivkala-creditMarianaPires-2.jpg",
    alt: "Rivkala seated in a tailored black suit against a pale studio background",
    label: "Press portrait 01",
    credit: "Photo: Mariana Pires",
    download_name: "rivkala-press-photo-01-mariana-pires.jpg",
    updated_at: seededAt,
  },
  {
    slot: 2,
    src: "/IMAGES%20OF%20ME/Rivkala-creditMarianaPires-3.jpg",
    alt: "Close portrait of Rivkala wearing a black suit and patterned tie",
    label: "Press portrait 02",
    credit: "Photo: Mariana Pires",
    download_name: "rivkala-press-photo-02-mariana-pires.jpg",
    updated_at: seededAt,
  },
  {
    slot: 3,
    src: "/IMAGES%20OF%20ME/Rivkala-creditMarianaPires-4.jpg",
    alt: "Rivkala applying lipstick in a wide editorial portrait",
    label: "Editorial landscape",
    credit: "Photo: Mariana Pires",
    download_name: "rivkala-editorial-landscape-mariana-pires.jpg",
    updated_at: seededAt,
  },
  {
    slot: 4,
    src: "/IMAGES%20OF%20ME/Rivkala-creditMarianaPires-5.jpg",
    alt: "Rivkala looking down while adjusting a patterned tie",
    label: "Editorial portrait",
    credit: "Photo: Mariana Pires",
    download_name: "rivkala-editorial-portrait-mariana-pires.jpg",
    updated_at: seededAt,
  },
];

export const epkStatic = {
  achievements: [
    "Two BBC Proms performances",
    "Best Music Video - Youth Music Awards",
    "BBC Introducing \"One to Watch\"",
    "MOBO fringe and Manchester Jazz Festival",
    "Support for Postmodern Jukebox at The Glasshouse",
    "Radio coverage across BBC Radio 3, Jazz FM and Selector Radio",
  ],
  quotes: [
    {
      text: "No ordinary jazz musician.",
      source: "BBC Introducing",
    },
    {
      text: "The funkiest cabaret I've ever been invited to.",
      source: "Soweto Kinch, Round Midnight",
    },
    {
      text: "A striking stage presence that harks back to the grand age of cabaret.",
      source: "Press quote",
    },
  ],
  contactEmail: "rivkala.music@gmail.com",
};
